apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-slackbot
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8081
  liveness:
    path: /isalive
    port: 8081
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8081
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  filesFrom:
    - secret: slackbot-secret
      mountPath: /var/run/secrets/slackbot-secret
  envFrom:
    - secret: slackbot-secret
  accessPolicy:
    inbound:
      rules:
        - application: samtykke-employee
        - application: samtykke-api
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com

